### ISSUE TITLE
"Show only menus from current screen" broken when used on empty screen?

### ISSUE THREAD

**Issue by zeparu** [psifidotos/applet-window-appmenu#170] opened 2021-07-08 18:11 UTC
![Screenshot_20210708_200719](https://user-images.githubusercontent.com/21054889/124970709-89ca9200-e028-11eb-8f55-2eeebaaa6af0.png)
![Screenshot_20210708_201058](https://user-images.githubusercontent.com/21054889/124970765-9ea72580-e028-11eb-8a97-7994e68f9c26.png)

**Comment by psifidotos** [comment] 2021-07-10 12:50
steps to reproduce

**Comment by zeparu** [comment] 2021-07-10 12:56
for me:

have a applet on both monitors, both configured the same as in the 2nd screenshot
have no application open on one monitor
have an application with an appmenu open and active on the other monitor

result:

even though the applet for window title is showing correct behaviour and showing the empty placeholder, the applet for appmenu is showing the appmenu for the active application on both monitors

expected result:

appmenu only shows for applications of the current screen, like configured in the settings

versions:
`plasma5-applets-window-appmenu` is latest git commit
`plasma-desktop` is `5.21.5-1`
os is manjaro

**Comment by zeparu** [comment] 2021-07-10 12:58
also, to further the weird behaviour:

if i have a single window with an appmenu open on the otherwise empty screen, it will properly show the appmenu in the applet
if i move the window over to the other screen, the appmenu will stop being displayed
clicking on the empty desktop (and so, defocusing the active application), will still not display the appmenu
clicking back onto the application on the other screen will show the appmenu now again on the empty screen

**Comment by psifidotos** [comment] 2021-07-10 14:27
Are you using plasma panels?

**Comment by zeparu** [comment] 2021-07-10 14:48
no, this is with only latte panels and docks

**Comment by psifidotos** [comment] 2021-07-10 15:41
Probably because, Show only menus from active applications is disabled

I will have to test things

**Comment by psifidotos** [comment] 2021-07-10 15:43
What is your Latte version?

**Comment by zeparu** [comment] 2021-07-10 15:47
its `latte-git` from the aur, latest commit on master branch

**Comment by psifidotos** [comment] 2021-07-10 15:53
If you enable, Show menus only for active applications, is it fixed?

**Comment by zeparu** [comment] 2021-07-10 15:58
yes, that will fix that behaviour, but then will also have the side effect, of not showing any *intended* appmenus on my not-active screen for applications i have open there

**Comment by psifidotos** [comment] 2021-07-10 16:03
Ok that makes it a subissue, needs investigation

**Comment by rodrigopedra** [comment] 2021-07-11 01:02
Hi @psifidotos , long time latte and appmenu user here.

I always had a similar issue, but as it didn't bother me so much I never considered reporting it.

I have a 4 monitor setup, so I made a video showing how to reproduce.

It seems new windows fill the menu on empty screens as seen in the video down below.

I created a totally new user to record the video, so no custom settings would mix.

I am also using the latest git versions for both latte-dock and appmenu as seen in the last part of the video. I use KDE neon with latest updates, as seen in the info center screen I use to demonstrate the issue. Only difference from stock KDE neon is that I use system76 repo to use the latest kernel, but I assume that is not an issue.

Basicaly the steps are:

- Add an empty panel
- Add appmenu widget
- Configure widget to use:
  - Check: "Always use maximum available width"
  - Check: "Show only menus from current screen"
  - Uncheck all the other options
- Edit latte layout
- Duplicate this panel on all other screens
- Open an app that exports its app menu
  - Newly open window should span its app menu to all screens

Let me know if the video is helpful, or if I can provide any further info.


https://user-images.githubusercontent.com/5470108/125179949-84a54880-e1ca-11eb-83f9-d36ce3318d48.mp4

**Comment by rodrigopedra** [comment] 2021-07-11 01:17
Further remarks:

- As you can see in the video, when a new window is opened, its app menu is replicated on all screens. But after moving the window from one screen into another, the previous screen's app menu is "cleared out"
- Reason `git pull` failed is that I was recording into the new user's session, but the repo is on my regular user, but I used `git log` to show the version installed
- There is another odd behavior I forgot to record on the video above, but recorded a new video below:
  - If other screen's app menu are "cleared out" by moving a window through screens, and then I open a new window and close it, the empty screens' appmenus get filled with the previous opened app's menu.

Hope this helps


https://user-images.githubusercontent.com/5470108/125180130-aa335180-e1cc-11eb-8690-10c6c817c039.mp4

**Comment by rodrigopedra** [comment] 2021-07-11 01:26
One more video with a different workflow:

- Open one window that exports its app menu
- "Clear out" other screens
- Open a new window that exports its app menu 
- "Clear out" other screens, but end on a different screen
- Close one window
  - The screen's appmenu widget from where the app was closed will be empty (as expected)
  - The screen's appmenu widget with the other app will be filled with the other app's menu (as expected)
  - The empty screen's appmenu widgets which were cleared out will fallback to the remaining app's menu


https://user-images.githubusercontent.com/5470108/125180215-e0250580-e1cd-11eb-98b4-8eddb6224102.mp4

**Closed** 2021-07-11 08:18 UTC

**Comment by rodrigopedra** [comment] 2021-07-11 15:18
Hey @psifidotos , just checked it out, and it works pretty well! Thank you very much.

Hope the info and videos provided helped somehow.

Have a nice day =)

**Comment by zeparu** [comment] 2021-07-13 18:28
i have to say that with my original problem seems like its still persisting, i have made a recording for it too

https://user-images.githubusercontent.com/21054889/125505698-61e8d5c6-6d17-4fc3-9729-5d462d797446.mp4


maybe it could also be that we have different understandings of what the option to only show menus from the active screen should do

**Comment by psifidotos** [comment] 2021-07-13 18:43
The issues you are demonstrating have been fixed, did you update properly?

**Comment by zeparu** [comment] 2021-07-13 18:47
to be sure, just did a fresh reinstall of `latte-dock-git`, and it still behaves that way

**Comment by rodrigopedra** [comment] 2021-07-13 19:49
Hey @zeparu , have you tried installing this applet (https://github.com/psifidotos/applet-window-appmenu) from its git repo?

Changes were made on the applet itself, not on Latte Dock.

**Comment by zeparu** [comment] 2021-07-13 19:59
oh oops, confused the packages, will try in a bit

**Comment by zeparu** [comment] 2021-07-13 20:10
yeah i had `plasma5-applets-window-appmenu` (not the git version), installing the git version fixed the issue.

@psifidotos issue's fixed, my bad for confusing the packages

**Comment by rodrigopedra** [comment] 2021-07-13 20:11
Glad you got it working! Have a nice day =)
