### ISSUE TITLE
Is the applet adding new global menu features?

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/applet-window-appmenu#28] opened 2018-12-02 09:54 UTC
I know that the global menu that applet uses is from newer stock, but is it automatically implementing the plasma global menu code (so nothing has to be done, when global menu are updated, this will be applied in the applet) or must it be done manually?

In the latter case, there were some small improvements in the global menu:

https://bugs.kde.org/show_bug.cgi?id=399975

Just to be on the freshest side of the code ;).

**Comment by psifidotos** [comment] 2018-12-02 10:01
Duplicate of #22

**Closed by psifidotos** 2018-12-02 10:01 UTC
